apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/att-user-consume
  newTag: b40f925e


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: att-user-consume-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: att-user-consume-secret-env
