# don't forget to update config.model
environment: local

app:
  name: test

server:
  port: 8080
  timeout: 15

log:
  environment: production
  level: info
  format: json


kafka:
  address: 
    - kafka.poc.internal:9092
  topic: example-topic


postgres:
  host: 172.28.240.42
  port: 5432
  db-name: att-db


redis:
  address: 172.28.241.3:6379
  database: 1

product-list-key: ATT_USER_LIST


