apiVersion: apps/v1
kind: Deployment
metadata:
  name: att-user-consume
  labels:
    app.kubernetes.io/name: att-user-consume
    app.kubernetes.io/instance: att-user-consume
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: att-user-consume
      app.kubernetes.io/instance: att-user-consume
  template:
    metadata:
      labels:
        app.kubernetes.io/name: att-user-consume
        app.kubernetes.io/instance: att-user-consume
    spec:
      containers:
        - name: att-user-consume
          image: asia.gcr.io/poc-innovation-iot/att-user-consume:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: att-user-consume-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: att-user-consume-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 64m
              memory: 64Mi
            requests:
              cpu: 32m
              memory: 32Mi
      volumes:
        - name: att-user-consume-secret-file
          secret:
            secretName: att-user-consume-secret-file
        - name: att-user-consume-configmap-file
          configMap:
            name: att-user-consume-configmap-file

        